name: taskshare
description: A new Flutter project.
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_auth:
  google_sign_in:
  scoped_model:
  logging:
  path_provider:
  rxdart:
  cloud_firestore:
  #  cached_network_image:
  shared_preferences:
  intl:
  built_value:
  quiver:
  tuple:
  bloc_provider:
  simple_logger:
  observable:
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation:
  build:
  build_runner:
  source_gen:
flutter:
  uses-material-design: true
